env_name: 'Hopper-v4'
env_parameters:
  ctrl_cost_weight: 0.075

seed: 408
exp_name: hopper_medium
run_id: ??? # decided during execution

train_episodes: 2000
gamma: 0.99
lr: 2e-3

testing: false
model_path: default

save_video: true
save_logging: true
save_model: true
use_wandb: true
silent: false

run_suffix: 0
# ref: https://stackoverflow.com/questions/65104134/disable-file-output-of-hydra
hydra:  
    output_subdir: null  
    run:  
        dir: .
